app/config - Twiddle D7 `CMS_VERSION`
In both CI and my local, drush is now reporting failures on this step:

```
drush8 -y dl drupal-7.x --destination=/home/jenkins/bknix-dfl/build/tmp-0-0 --drupal-project-rename
```

The exact error depends on the PHP version:

```
-- php74
copy(): Filename cannot be empty drush.inc:768

-- php80
Error: Uncaught ValueError: Path cannot be empty in phar:///Users/totten/bknix/extern/drush8.phar/includes/drush.inc:768
```

Switching the version expression to `drupal-7` or `drupal-7.89` appears to fix it.