Switch loco to PHAR-based download
This is a workaround for the following build error:

```
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Package operations: 14 installs, 0 updates, 0 removals
  - Installing marcj/topsort (1.1.0): Downloading (failed)
Downloading (failed)
Downloading (failed)    Failed to download marcj/topsort from dist: The "https://api.github.com/repos/marcj/topsort.php/zipball/387086c2db60ee0a27ac5df588c0f0b30c6bdc4b" file could not be downloaded: php_network_getaddresses: getaddrinfo failed: Name or service not known
failed to open stream: php_network_getaddresses: getaddrinfo failed: Name or service not known
    Now trying to download from source
  - Installing marcj/topsort (1.1.0): Cloning 387086c2db

  [RuntimeException]
  Failed to clone https://github.com/marcj/topsort.php.git via https, ssh protocols, aborting.

  - https://github.com/marcj/topsort.php.git
    Cloning into '/build/loco-src/vendor/marcj/topsort'...
    fatal: unable to access 'https://github.com/marcj/topsort.php.git/': Could not resolve host: github.com

  - git@github.com:marcj/topsort.php.git
    Cloning into '/build/loco-src/vendor/marcj/topsort'...
    ssh: Could not resolve hostname github.com: Name or service not known
    fatal: Could not read from remote repository.

    Please make sure you have the correct access rights
    and the repository exists.

install [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-progress] [--no-suggest] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--ignore-platform-reqs] [--] [<packages>]...

builder for '/nix/store/zbwvnm9ri919a1ahpalxdzmgfc127zm0-loco.drv' failed with exit code 1
error: build of '/nix/store/zbwvnm9ri919a1ahpalxdzmgfc127zm0-loco.drv' failed
```