homerdo - Re-tune guards before `ps -p`
We're getting some warnings in the logs like this:

```
[dispatcher] Finding home-image in /home/dispatcher/images...
cat: /var/local/homer/fa6e218ee3821a84cf1cbbd4d288b7d9/lock: No such file or directory
error: list of process IDs must follow -p

Usage:
 ps [options]

 Try 'ps --help <simple|list|output|threads|misc|all>'
  or 'ps --help <s|l|o|t|m|a>'
 for additional help text.

For more details see ps(1).
[dispatcher] Found home-image /home/dispatcher/images/bknix-php82m57-0.img
```

This doesn't really make sense because the calls to `ps -p`  have guards.
But maybe the guards are somehow off.

The change goes at two angles -- prefering to use `-e` instead of `-f`, and preferring
built-in conditionals (`[[ ... ]]`) rather than external conditionals (`[ ... ]`).